name: auto build engine

on: 
  #release:
  #  types: [published]
  ##schedule:
  ##  - cron: "0 16 * * *"
  #push:
  #  branches: 
  #    - master
  #watch:
  #  types: [started]
  
  workflow_dispatch:
  
jobs:
  build:
    #runs-on: ubuntu-24.04
    runs-on: debian bookworm
    
    steps:
    - name: Build Armbian
      run: |
        git clone https://github.com/armbian/build --depth 1
        wget https://raw.githubusercontent.com/ActiveIce/rockpi-4b-plus/master/fix-rtl8211f.patch
        wget https://raw.githubusercontent.com/ActiveIce/rockpi-4b-plus/master/rockpi-4b-plus.csc
        cp fix-rtl8211f.patch build/patch/kernel/
        cp rockpi-4b-plus.csc build/config/boards/
        cd build
        ./compile.sh BOARD=rockpi-4b-plus \
          BRANCH=current \ #edge
          RELEASE=bookworm \ #jammy
          BUILD_MINIMAL=no \
          BUILD_DESKTOP=no \
          KERNEL_CONFIGURE=no \
          INSTALL_HEADERS=yes \
          COMPRESS_OUTPUTIMAGE=xz #sha,gpg,img
        
    - name: Upload Armbian
      uses: actions/upload-artifact@main
      with:
        name: image
        path: build/output/images/*.img

